server:
  port: 8016

spring:
  datasource:
    url: jdbc:mysql://${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none        # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        auto_quote_keyword: false
        globally_quoted_identifiers: false
        format_sql: true     # 쿼리 로그 포맷 (정렬)
        show_sql: true       # 쿼리 로그 출력
## mybatis config
mybatis:
  type-aliases-package: com.sprint.odigo
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    multiple-result-sets-enabled: true
    call-setters-on-nulls: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace