export const iconPath = {
  '01호선': require('./assets/img/line_01.png'),
  '02호선': require('./assets/img/line_02.png'),
  '03호선': require('./assets/img/line_03.png'),
  '04호선': require('./assets/img/line_04.png'),
  '05호선': require('./assets/img/line_05.png'),
  '06호선': require('./assets/img/line_06.png'),
  '07호선': require('./assets/img/line_07.png'),
  '08호선': require('./assets/img/line_08.png'),
  '09호선': require('./assets/img/line_09.png'),
  lineic1: require('./assets/img/line_ic1.png'),
  lineic2: require('./assets/img/line_ic2.png'),
  linekk: require('./assets/img/line_kk.png'),
  linekj: require('./assets/img/line_kj.png'),
  linearex: require('./assets/img/line_arex.png'),
  linekc: require('./assets/img/line_kc.png'),
};
