services:
  mysql:
    user: '501:20'
    image: mysql:8.0.33
    ports:
      - 13306:3306
    volumes:
      - /Users/hyewonkim/dev/odigo_docker/data:/var/lib/mysql:rw
      - /Users/hyewonkim/odigo/server/src/main/resources/initdb:/docker-entrypoint-initdb.d
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: odigo
      MYSQL_DATABASE: odigo
